/**
 * Generates placeholder PNG icons for the Chrome extension.
 * Uses only Node.js built-ins — no npm deps required.
 *
 * Run once:  node scripts/generate-icons.mjs
 *
 * For production, replace icons/ with proper branded PNGs.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(__dirname, "..", "icons");
mkdirSync(iconsDir, { recursive: true });

/**
 * Minimal valid 1×1 transparent PNG (base64).
 * We scale it by embedding an SVG as a data URI inside a PNG canvas via
 * a simple hand-crafted minimal PNG structure.
 *
 * Since we don't have canvas or sharp available here, we generate a
 * simple colored-square SVG and save it as an SVG for development.
 * Chrome accepts SVG icons in development (unpacked extension).
 */

const sizes = [16, 48, 128];

for (const size of sizes) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" rx="${Math.round(size * 0.18)}" fill="#1e293b"/>
  <text
    x="50%" y="54%"
    dominant-baseline="middle"
    text-anchor="middle"
    font-size="${Math.round(size * 0.6)}"
    font-family="system-ui, sans-serif"
    fill="#5b8cff"
  >⚡</text>
</svg>`;

  // Save as SVG (works for development / unpacked extension)
  writeFileSync(join(iconsDir, `icon${size}.svg`), svg);

  // For production builds, convert SVGs to PNGs using:
  //   npx sharp-cli --input icons/icon{16,48,128}.svg --output icons/
  // or use Inkscape: inkscape --export-type=png icon128.svg
  console.log(`✓  icons/icon${size}.svg`);
}

console.log(
  "\nFor production PNGs, convert SVGs with:\n" +
    "  npx @squoosh/cli --oxipng {} icons/*.svg\n" +
    "or rename .svg → .png and update manifest.json icons to .svg\n"
);

// Write a note about icon requirements
writeFileSync(
  join(iconsDir, "README.md"),
  `# Extension Icons

SVG placeholder icons are generated by \`scripts/generate-icons.mjs\`.

**For the Chrome Web Store**, you need PNG icons (not SVG):

1. Convert SVG → PNG using one of:
   - Inkscape: \`inkscape --export-type=png icon128.svg\`
   - ImageMagick: \`convert icon128.svg icon128.png\`
   - Online: https://svgtopng.com

2. Replace icon16/48/128.svg with .png files
3. Update \`manifest.json\` icon paths from \`.svg\` to \`.png\`

For development (unpacked extension), SVGs work fine.
`
);
